[tool.poetry]
name = "web-project"
version = "0.1.0"
description = ""
authors = ["Kira <kirillbutakov02021994@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
